freebsd_build_task:

  freebsd_instance:
    matrix:
      image_family: freebsd-15-0-snap
      image_family: freebsd-14-2-snap
    cpu: 4
    memory: 4G

  env:
    DEPENDENCIES: git gcc wget openssl python3 meson pkgconf
    PY_DEPS:      pyelftools
    matrix:
      COMPILER: gcc
      COMPILER: clang

  prepare_script:
    - sysctl -w kern.coredump=0
    - pkg update -f
    - pkg install -y ${DEPENDENCIES}
        $(pkg search -xq "^py3[0-9]+-(${PY_DEPS})-[0-9]+" | xargs)
    - mkdir -p /usr/src
    - git clone --depth 1 https://git.freebsd.org/src.git /usr/src

  configure_script:
    - ./.ci/freebsd-setup.sh

  build_script:
    - ./.ci/freebsd-build.sh

  check_script:
    - ./.ci/freebsd-test.sh
            || { cat ./build/meson-logs/testlog.txt; exit 1; }
