language: c
compiler:
  - gcc
  - clang

os:
  - linux

addons:
  apt:
    packages:
      - libnuma-dev
      - linux-headers-$(uname -r)

before_install: ./.ci/${TRAVIS_OS_NAME}-setup.sh

sudo: false

env:
  - SHARED=1
  - SHARED=0
  - KERNEL=1

matrix:
  include:
    - compiler: clang
    - language: python
      python: 3.5

script: ./.ci/${TRAVIS_OS_NAME}-build.sh $OPTS

#notifications:
#  email:
#    recipients:
            #- test-report@dpdk.org
