language: c

addons:
  apt:
    packages:
      - libnuma-dev                                             # numa is a dependency
      - linux-headers-generic                                   # get header files for travis virtual machine
script: /usr/bin/make defconfig && make all
